// Action Types
export const FETCH_GUIDE_TODAY = 'FETCH_GUIDE_TODAY'
export const FETCH_GUIDE_TODAY_SUCCESS = 'FETCH_GUIDE_TODAY_SUCCESS'
export const FETCH_GUIDE_TODAY_FAILURE = 'FETCH_GUIDE_TODAY_FAILURE'
export const FETCH_GUIDE_BY_MONTH = 'FETCH_GUIDE_BY_MONTH'
export const FETCH_GUIDE_BY_MONTH_SUCCESS = 'FETCH_GUIDE_BY_MONTH_SUCCESS'
export const FETCH_GUIDE_BY_MONTH_FAILURE = 'FETCH_GUIDE_BY_MONTH_FAILURE'
export const FETCH_GUIDE_BY_DATE = 'FETCH_GUIDE_BY_DATE'
export const FETCH_GUIDE_BY_DATE_SUCCESS = 'FETCH_GUIDE_BY_DATE_SUCCESS'
export const FETCH_GUIDE_BY_DATE_FAILURE = 'FETCH_GUIDE_BY_DATE_FAILURE'
export const FETCH_TODAY_CHAPTER = 'FETCH_TODAY_CHAPTER'
export const FETCH_TODAY_CHAPTER_SUCCESS = 'FETCH_TODAY_CHAPTER_SUCCESS'
export const FETCH_TODAY_CHAPTER_FAILURE = 'FETCH_TODAY_CHAPTER_FAILURE'
export const FETCH_CHAPTER_BY_DATE = 'FETCH_CHAPTER_BY_DATE'
export const FETCH_CHAPTER_BY_DATE_SUCCESS = 'FETCH_CHAPTER_BY_DATE_SUCCESS'
export const FETCH_CHAPTER_BY_DATE_FAILURE = 'FETCH_CHAPTER_BY_DATE_FAILURE'

// Setter Types
export const SET_GUIDE_DATE = 'SET_GUIDE_DATE'

export interface ActionTypes {
  type: string
  data?: any
}
