// Types
import type { PassageItem } from 'app/types'

export const passageData: PassageItem[] = [
  { name: 'search', abbr: '', passage: 0 },
  { name: 'Kejadian', abbr: 'kej', passage: 50 },
  { name: 'Keluaran', abbr: 'kel', passage: 40 },
  { name: 'Imamat', abbr: 'ima', passage: 27 },
  { name: 'Bilangan', abbr: 'bil', passage: 36 },
  { name: 'Ulangan', abbr: 'ula', passage: 34 },
  { name: 'Yosua', abbr: 'yos', passage: 24 },
  { name: 'Hakim-Hakim', abbr: 'hak', passage: 21 },
  { name: 'Rut', abbr: 'rut', passage: 4 },
  { name: '1 Samuel', abbr: '1sa', passage: 31 },
  { name: '2 Samuel', abbr: '2sa', passage: 24 },
  { name: '1 Raja-Raja', abbr: '1ra', passage: 22 },
  { name: '2 Raja-Raja', abbr: '2ra', passage: 25 },
  { name: '1 Tawarikh', abbr: '1ta', passage: 29 },
  { name: '2 Tawarikh', abbr: '2ta', passage: 36 },
  { name: 'Ezra', abbr: 'ezr', passage: 10 },
  { name: 'Nehemia', abbr: 'neh', passage: 13 },
  { name: 'Ester', abbr: 'est', passage: 10 },
  { name: 'Ayub', abbr: 'ayb', passage: 42 },
  { name: 'Mazmur', abbr: 'mzm', passage: 150 },
  { name: 'Amsal', abbr: 'ams', passage: 31 },
  { name: 'Pengkhotbah', abbr: 'pkh', passage: 12 },
  { name: 'Kidung Agung', abbr: 'kid', passage: 8 },
  { name: 'Yesaya', abbr: 'yes', passage: 66 },
  { name: 'Yeremia', abbr: 'yer', passage: 52 },
  { name: 'Ratapan', abbr: 'rat', passage: 5 },
  { name: 'Yehezkiel', abbr: 'yeh', passage: 48 },
  { name: 'Daniel', abbr: 'dan', passage: 12 },
  { name: 'Hosea', abbr: 'hos', passage: 14 },
  { name: 'Yoel', abbr: 'yoe', passage: 3 },
  { name: 'Amos', abbr: 'amo', passage: 9 },
  { name: 'Obaja', abbr: 'oba', passage: 1 },
  { name: 'Yunus', abbr: 'yun', passage: 4 },
  { name: 'Mikha', abbr: 'mik', passage: 7 },
  { name: 'Nahum', abbr: 'nah', passage: 3 },
  { name: 'Habakuk', abbr: 'hab', passage: 3 },
  { name: 'Zefanya', abbr: 'zef', passage: 3 },
  { name: 'Hagai', abbr: 'hag', passage: 2 },
  { name: 'Zakharia', abbr: 'zak', passage: 14 },
  { name: 'Maleakhi', abbr: 'mal', passage: 4 },
  { name: 'Matius', abbr: 'mat', passage: 28 },
  { name: 'Markus', abbr: 'mrk', passage: 16 },
  { name: 'Lukas', abbr: 'luk', passage: 24 },
  { name: 'Yohanes', abbr: 'yoh', passage: 21 },
  { name: 'Kisah Para Rasul', abbr: 'kis', passage: 28 },
  { name: 'Roma', abbr: 'rom', passage: 16 },
  { name: '1 Korintus', abbr: '1ko', passage: 16 },
  { name: '2 Korintus', abbr: '2ko', passage: 13 },
  { name: 'Galatia', abbr: 'gal', passage: 6 },
  { name: 'Efesus', abbr: 'efe', passage: 6 },
  { name: 'Filipi', abbr: 'flp', passage: 4 },
  { name: 'Kolose', abbr: 'kol', passage: 4 },
  { name: '1 Tesalonika', abbr: '1te', passage: 5 },
  { name: '2 Tesalonika', abbr: '2te', passage: 5 },
  { name: '1 Timotius', abbr: '1ti', passage: 6 },
  { name: '2 Timotius', abbr: '2ti', passage: 4 },
  { name: 'Titus', abbr: 'tit', passage: 3 },
  { name: 'Filemon', abbr: 'flm', passage: 1 },
  { name: 'Ibrani', abbr: 'ibr', passage: 13 },
  { name: 'Yakobus', abbr: 'yak', passage: 5 },
  { name: '1 Petrus', abbr: '1pt', passage: 5 },
  { name: '2 Petrus', abbr: '2pt', passage: 3 },
  { name: '1 Yohanes', abbr: '1yo', passage: 5 },
  { name: '2 Yohanes', abbr: '2yo', passage: 1 },
  { name: '3 Yohanes', abbr: '3yo', passage: 1 },
  { name: 'Yudas', abbr: 'yud', passage: 1 },
  { name: 'Wahyu', abbr: 'why', passage: 22 },
]

const apiEnv = process.env.EXPO_PUBLIC_API_ENV || 'production'
export const apiUrl =
  apiEnv === 'local' ? 'http://localhost:3000' : 'https://freedomlife.id'

export const guideValueArray = ['pl_name', 'pb_name', 'in_name']
